json.symbol @new_stock.symbol
json.company_name @new_stock.company_name
json.year_high @new_stock.year_high
json.year_low @new_stock.year_low
json.asking_price @new_stock.asking_price
json.bidding_price @new_stock.bidding_price
json.average_daily_volume @new_stock.average_daily_volume
json.days_low @new_stock.days_low
json.days_high @new_stock.days_high
json.days_percent @new_stock.changein_percent